apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-du-performance-addon-policy
  namespace: du-subscriptions
placementRef:
  name: placement-policy-du-performance-addon-policy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-config-performanceprofile-du
  kind: Policy
  apiGroup: policy.open-cluster-management.io
