apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-cu-performance-addon-policy
  namespace: cu-subscriptions
spec:
  clusterSelector:
    matchExpressions:
      - {key: profile, operator: In, values: [cu]}
