apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-du-rt-kernel-policy
  namespace: du-subscriptions
spec:
  clusterSelector:
    matchExpressions:
      - {key: profile, operator: In, values: [du]}
