apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00_mcp_cu_policy.yaml
  - 01_mcp_cu_placementbinding.yaml
  - 02_mcp_cu_placementrule.yaml
  - 03_sriov_operator_config_policy.yaml
  - 04_sriov_operator_config_policy_placementbinding.yaml
  - 05_sriov_operator_config_policy_placementrule.yaml
  - 06_performance_profile_policy.yaml
  - 07_performance_profile_placementbinding.yaml
  - 08_performance_profile_placementrule.yaml
  - 12_sctp_module_policy.yaml
  - 13_sctp_module_placementbinding.yaml
  - 14_sctp_module_placementrule.yaml
